# Generated by Django 4.1.4 on 2022-12-11 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_favoriteitem_favoritepart_delete_userfavorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepart',
            name='loop_end_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='favoritepart',
            name='loop_start_time',
            field=models.IntegerField(),
        ),
    ]
