# Generated by Django 4.1.4 on 2022-12-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_favoritepart_loop_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritepart',
            name='media_type',
            field=models.CharField(max_length=12),
        ),
    ]
