"""
Django settings for justjam_proj project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path
from .settings_common import *
from .local_settings import SECRET_KEY as sk
from .local_settings import TEAM_ID as team_id
from .local_settings import KEY_ID as key_id
from .local_settings import AUTH_KEY_FILE as auth_key_file
from .local_settings import JWT_JSON_FILE as jwt_json_file


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = sk

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost','127.0.0.1']

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = ['http://localhost:8080']

CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = ['http://localhost:8080']

TEAM_ID = team_id
KEY_ID = key_id
AUTH_KEY_FILE = auth_key_file
JWT_JSON_FILE = jwt_json_file